### ISSUE TITLE
Panic on unmarshalling

### ISSUE THREAD

**Issue by Isolus** [mitch000001/go-hbci#17]
Hi,

the Postbank sends messages like this: `HIUPD:47:5:4++Login+++Name++++HKPSA:1'`.
The missing account and the missing currency lead to a panic if you call `.Account()` on the result (like it is done in [dialog/dialog.go#L461](https://github.com/mitch000001/go-hbci/blob/180d8316ddfed7fd5766dd69734fe5ed35467429/dialog/dialog.go#L461)).

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x115a1a5]

goroutine 21 [running]:
testing.tRunner.func1(0xc0000b6500)
	/usr/local/go/src/testing/testing.go:792 +0x387
panic(0x11b2200, 0x1371910)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/mitch000001/go-hbci/segment.(*AccountInformationV5).Account(0xc00007d500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/me/go-repos/go-hbci/segment/basic_account_information.go:101 +0x225
github.com/mitch000001/go-hbci/segment.TestAccountInformationSegmentUnmarshalHBCI(0xc0000b6500)
	/home/me/go-repos/go-hbci/segment/basic_account_information_unmarshaler_test.go:36 +0x796
testing.tRunner(0xc0000b6500, 0x11f8450)
	/usr/local/go/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:878 +0x35c
exit status 2
```

(I modified the test string in `TestAccountInformationSegmentUnmarshalHBCI` and added a call to `.Account()` to debug this error.)

**Comment by mitch000001** [comment]
Sorry it took so long. Fixed in https://github.com/mitch000001/go-hbci/releases/tag/v0.3.2
